### ISSUE TITLE
Change unique default SSID name and password

### ISSUE THREAD

**Issue by bartoszcisek** [PTR-projects/PTR_mega_firmware#29]
# Summary
It could happen that on a single event (ie Festiwal Meteora) there would be multiple devices running our firmware. Default SSID name is `KPPTR` which would result with multiple Access Points (AP) with same SSID. As a result preconfigured phone may try to connect to different device than expected.

Unexpected connection to different device may be even dangerous given possibility of remote arming.

# Solution
Default SSID name could be sufixed with two last octets of WiFi mac address.  Arming option could be disabled as long as default password is not changed.

**Comment by bartekM-pl** [comment]
Default KPPTR prefix should be changed too and should reflect board type ex. PTR-mega-XXXX, PTR-GS-XXXX
